name: codebuild

on:
  push:
    branches:
      - master
env:
  REPOSITORY: openorclose/async-profiler
  RELEASE_ID: 174369452
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-arm:
    runs-on: codebuild-test-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-small
    steps:
      - run: |
            echo "Hello World"
