name: codebuild

on:
  push:
    branches:
      - master
jobs:
  build-arm:
    runs-on: codebuild-test-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      REPOSITORY: openorclose/async-profiler
      RELEASE_ID: 174369452
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Build, Test, and Publish
        run: |
          sudo sysctl kernel.perf_event_paranoid=1 && sudo sysctl kernel.kptr_restrict=0 # allow tests to execute
          make COMMIT_TAG=true CC=/usr/local/musl/aarch64/bin/musl-gcc release test publish-github-artifact # build and publish arm64 binaries
          #echo "123" > test.txt
          #curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/zip" --data-binary "@test.txt" "https://uploads.github.com/repos/$REPOSITORY/releases/$RELEASE_ID/assets?name=test.txt"
