name: codebuild

on:
  push:
    branches:
      - master
env:
  REPOSITORY: openorclose/async-profiler
  RELEASE_ID: 174369452
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-arm:
    runs-on: codebuild-test-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-small
    steps:
      - uses: actions/checkout@v4
      - name: Build, Test, and Publish
        run: |
          sudo yum install -y sudo patchelf make g++ g++-aarch64-linux-gnu openjdk-11-jdk-headless
          rm -rf /var/cache/apt /var/lib/apt/lists/*
          # apt-get update && apt-get install -y git curl jq # curl for publishing artifacts, git for checkout out source, jq to parse github api responses
          # git clone https://github.com/${REPOSITORY}.git && cd async-profiler && git checkout $GITHUB_SHA # checkout sources
          sudo sysctl kernel.perf_event_paranoid=1 && sudo sysctl kernel.kptr_restrict=0 # allow tests to execute
          make COMMIT_TAG=true release publish-github-artifact # build and publish arm64 binaries

