name: Publish Nightly Builds

on:
  push:
    branches:
      - master
env:
  REPOSITORY: openorclose/async-profiler
  PAST_RELEASES_ID: 174369452
  LATEST_RELEASE_ID: 176384274
jobs:
  build-test-publish:
    strategy:
      matrix:
        include:
          - runson: macos-latest
            image: ${{ null }}
          - runson: ubuntu-latest
            image: docker://public.ecr.aws/async-profiler/asprof-builder-x86:latest
            arch: x86_64
          - runson: codebuild-test-${{ github.run_id }}-${{ github.run_attempt }}
            arch: aarch64
            iamge: ${{ null }}
    env:
      REPOSITORY: openorclose/async-profiler
      LATEST_RELEASE_ID: 174369452
    runs-on: ${{ matrix.runson }}
    container:
      image: ${{ matrix.image }}
      options: --privileged # needed in order to use sysctl
    steps:
      - uses: actions/checkout@v4
      - name: Build, test, and publish
        run: |
          if [[ "${{ matrix.runson }}" != "macos-latest" ]]; then # configuration needed only for linux
            sudo sysctl kernel.perf_event_paranoid=1 && sudo sysctl kernel.kptr_restrict=0 # allow tests to execute
            CC=/usr/local/musl/${{ matrix.arch }}/bin/musl-gcc
          fi
          make COMMIT_TAG=true GITHUB_TOKEN=${{ github.token }} release publish-github-artifact # build, test, and publish x86 binaries
