name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: docker://public.ecr.aws/async-profiler/asprof-builder:latest
        options: --user root --security-opt seccomp=unconfined
    steps:
      - name: ls
        run: apt-get update && apt-get install -y git curl jq && git clone https://github.com/openorclose/async-profiler.git && cd async-profiler && git checkout $GITHUB_SHA &&
             make CC=/usr/local/musl/x86_64/bin/musl-gcc -j release &&
             sudo sysctl kernel.perf_event_paranoid=1 && sudo sysctl kernel.kptr_restrict=0 && make test &&
             make clean &&
             make ARCH_TAG=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=/usr/local/musl/aarch64/bin/musl-gcc -j release
      - name: Zip
        run: tar -czvf release.tar.gz async-profiler/build
      - name: Release
        env:
          UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
          DEBUG: api
        run: |
          id=$(curl -L  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/openorclose/async-profiler/releases/174369452/assets | jq ".[0].id")
          curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/openorclose/async-profiler/releases/assets/${id}"
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary "@release.tar.gz" "https://uploads.github.com/repos/openorclose/async-profiler/releases/174369452/assets?name=release.tar.gz"
