name: Publish Nightly Builds

on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
        image: docker://public.ecr.aws/async-profiler/asprof-builder:latest
        options: --user root --privileged --security-opt seccomp=unconfined # needed in order to use sysctl
    steps:
      - name: Build
        run: |
             apt-get update && apt-get install -y git curl jq # curl for publishing artifacts, git for checkout out source, jq to parse github api responses
             git clone https://github.com/openorclose/async-profiler.git && cd async-profiler && git checkout $GITHUB_SHA # checkout sources
             make CC=/usr/local/musl/x86_64/bin/musl-gcc -j release # build x86 binaries
             sudo sysctl kernel.perf_event_paranoid=1 && sudo sysctl kernel.kptr_restrict=0 # allow tests to execute
             make test
             make clean
             make ARCH_TAG=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=/usr/local/musl/aarch64/bin/musl-gcc -j release # build arm64 binaries
      - name: Publish Artifacts
        env:
          UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
          DEBUG: api
        run: |
          # get the ids of all published artifacts in the nightly release
          ids=$(curl -L  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/openorclose/async-profiler/releases/174369452/assets | jq ".[].id")
          # delete all assets in the nightly release
          for id in $ids; do curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/openorclose/async-profiler/releases/assets/${id}"; done
          # publish x86 binaries
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary "@async-profiler/async-profiler-3.0-linux-arm64.tar.gz" "https://uploads.github.com/repos/openorclose/async-profiler/releases/174369452/assets?name=async-profiler-3.0-linux-arm64.tar.gz"
          # publish arm64 binaries
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary "@async-profiler/async-profiler-3.0-linux-x64.tar.gz" "https://uploads.github.com/repos/openorclose/async-profiler/releases/174369452/assets?name=async-profiler-3.0-linux-x64.tar.gz"
