name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # container:
      #  image: docker://public.ecr.aws/async-profiler/asprof-builder:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch
        run: docker build . -t local --output type=local,dest=.
      - name: Zip
        run: tar -czvf release.tar.gz build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.tar.gz
