name: Publish Nightly Builds (Mac)

on: push

jobs:
  build-and-publish:
    runs-on: macos-latest
    steps:
      # Unfortunately we cannot use this action to clone the repository due to the actions requiring Node 20 which this container doesn't support
      # https://github.com/actions/checkout/issues/1590
      # https://github.com/actions/checkout/issues/1590#issuecomment-2293211398
      
      # - name: Checkout
      #  uses: actions/checkout@v3
      
      # Instead, we have to clone using git manually
      - name: Build
        run: |
            java -version
            git clone https://github.com/openorclose/async-profiler.git && cd async-profiler && git checkout $GITHUB_SHA # checkout sources
            make release
            sudo sysctl kernel.perf_event_paranoid=1 && sudo sysctl kernel.kptr_restrict=0 # allow tests to execute
            make test
      # Unfortunately we cannot use this action upload artifacts to the release due to the actions requiring Node 20 which this container doesn't support
      # https://github.com/actions/checkout/issues/1590
      # https://github.com/actions/checkout/issues/1590#issuecomment-2293211398
      
      # - name: Publish Artifacts
      #   uses: softprops/action-gh-release@v2

      # Instead, we have to manually call the REST endpoints at https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28
      - name: Publish Artifacts
        run: |
            # get the ids of all published artifacts in the nightly release
            ids=$(curl -L  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/openorclose/async-profiler/releases/174369452/assets | jq ".[].id")
            # delete all assets in the nightly release
            # for id in $ids; do curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/openorclose/async-profiler/releases/assets/${id}"; done
            # publish x86 binaries
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary "@async-profiler/release.tar.gz" "https://uploads.github.com/repos/openorclose/async-profiler/releases/174369452/assets?name=async-profiler-3.0-macos.tar.gz"
            # publish arm64 binaries
            # curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary "@async-profiler/async-profiler-3.0-linux-x64.tar.gz" "https://uploads.github.com/repos/openorclose/async-profiler/releases/174369452/assets?name=async-profiler-3.0-linux-x64.tar.gz"
